language: go

go:
  - 1.14.x
  - master

# Allow builds from tip to fail - they might be in an unstable state
jobs:
  allow_failures:
    - go: master

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

env:
  global:
    - GO111MODULE=on

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then CGO_ENABLED=0 go build -ldflags="-w -s" -o ew-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH.exe . ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then CGO_ENABLED=0 go build -ldflags="-w -s" -o ew-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH . ; fi
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: L5dAHmwjT55Ipau4TB/7wFbY15BuyvCJu/XitCZJaxnHItNBsqRoWhx1rOhkz3IEN1n7Vt4wpMK8jv/51wZS/yQNwBftybHrYu5xtg8g71jOOH1a38xNZla/Hm54K9ZgA1zXpgfhnXywao/+kdLah3JYLmNXYtnr/BZNB6s0ct/fD6UYkWJ8pyP0kRQgxJ71ZEMHkuHpXxGOJgQ+O2UwEO8FqNJxBum+7e40xQY5plhbLGUf6bP8icdtr/p1TFOlbjguhIxJdxz7UQ1yTGKA+IXMXs6hEc8uQZjwSiu6a+/x9FS84hW8NZ2ynnHt+xtYdDTGP6sHQYsfWHkdUv189doe/ITCub927+gJdneZuNECLw/zl1WGXl0CklFNIdynQ1Xfpe/i0vMY504Irl/dro2uxuIroFOxidopwnn7rqOWLRpm+sLh++L8cjWV8IyEq3mpnE5blJQLW4QR8WsVFjfNLAMmHgXY6af+NOMjzFaH6HPAjtaeKPO8suVbJ2BDkwVHEmWnmoEb0ovKkQmMMZcnfWOblApUmtHTtgj4QSK5BnCI9EKXelzhXLpkdY8EyU1K17myXwF8+a+efGtMwwTDyoUDraGDzOvlj5plmOsEA/eahD4Rp6P8URHQoLvRnZOn5yBwXIjZwcQk9xIzy5E2LXroHl7uE8nQTSWi7aA=
  file_glob: true
  file: ew*
  skip_cleanup: true
  on:
    repo: kernle32dll/ew
    tags: true
    go: 1.14.x